DROP TABLE IF EXISTS sms_statuses;
CREATE TABLE playlists(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	message_id INTEGER NOT NULL,
	recipient_id INTEGER NOT NULL,
	status VARCHAR(10) NOT NULL,
	occurred_at INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);