DROP TABLE IF EXISTS sms_statuses;
CREATE TABLE playlists(
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	message_id INTEGER NOT NULL,
	recipient_id INTEGER NOT NULL,
	status VARCHAR(50) CHECK (status IN ('DELIVERED_TO_SERVER','SENT_TO_RECIPIENT','DELIVERED_TO_RECIPIENT','FAILED_TO_SEND_TO_RECIPIENT')) NOT NULL,
	occurred_at INTEGER NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);